name: Jekyll Site CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the site in a Docker container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "jekyll build --future"

      - name: Deploy the site
        uses: actions/deploy@v1
        with:
          provider: pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: _site
